### ISSUE TITLE
Serializing DTSTART into UTC violates recurrences on daylight saving time

### ISSUE THREAD

**Issue by stefan-walluhn** [django-recurrence/django-recurrence#174]
In several time zones the concept of daylight saving time is known. Recurrence should be stable when switching back and forth to daylight saving time, but are not when using `django-recurrence`. 

When serializing timezone aware DTSTART datetimes objects, `django-recurrence` converts these times to UTC. This happens in the backend:

https://github.com/django-recurrence/django-recurrence/blob/f3b51169ed6a29305950b9d839875a0be1d960ea/recurrence/base.py#L834-L846

as well as in the JavaScript frontend 

https://github.com/django-recurrence/django-recurrence/blob/f3b51169ed6a29305950b9d839875a0be1d960ea/recurrence/static/recurrence/js/recurrence.js#L574-L579

Doing so, the recurrences are shifted back and forth on local time zone changes:

```
>>> from dateutil.rrule import rrulestr
>>> import pytz
>>> rr = rrulestr("""
... DTSTART:20201023T070000Z
... RRULE:FREQ=DAILY;COUNT=4
... """)
>>> list(map(lambda d: d.astimezone(pytz.timezone('Europe/Berlin')), rr))
[datetime.datetime(2020, 10, 23, 9, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CEST+2:00:00 DST>), datetime.datetime(2020, 10, 24, 9, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CEST+2:00:00 DST>), datetime.datetime(2020, 10, 25, 8, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), datetime.datetime(2020, 10, 26, 8, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>)]
```
(Have a look on how the hour is changing from October, 24th to October, 25th)

https://tools.ietf.org/html/rfc5545#section-3.8.5.3 mentioned to add proper time zone reference to avoid these kind of time shifts:

> In most cases, a "DTSTART" property of DATE-TIME value type used with a recurrence rule, should be specified as a date with local time and time zone reference to make sure all the recurrence instances start at the same local time regardless of time zone changes.

Python's dateutil library also represents the expected behavior:

```
>>> from dateutil.rrule import rrulestr
>>> import pytz
>>> rr = rrulestr("""
... DTSTART;TZID=Europe/Berlin:20201023T090000
... RRULE:FREQ=DAILY;COUNT=4
... """)
>>> list(map(lambda d: d.astimezone(pytz.timezone('Europe/Berlin')), rr))
[datetime.datetime(2020, 10, 23, 9, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CEST+2:00:00 DST>), datetime.datetime(2020, 10, 24, 9, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CEST+2:00:00 DST>), datetime.datetime(2020, 10, 25, 9, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), datetime.datetime(2020, 10, 26, 9, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>)]
```
(Local hours are stable across  time zone changes)

To follow RFC 5545 and maintain stable recurrences, `django-recurrence` should not convert timezone aware DTSTART values to UTC, but should serialize the rrules containing the correct time zone reference.

**Comment by Mapiarz** [comment]
Good write up but that's just one example where this package fundamentally breaks.

If your local timezone is different from server, everything gets screwed up as well.
For instance: My local timezone is 6 hours ahead of server time. When I set up a 'weekly, each Friday' rule and an `exdate` to December 25th and save the object, the underlying exdate is 2020/12/24 18:00. Because of that, that `exdate` (or `rdate`) will never be recognized properly. Even if `USE_TZ = True`, the `exdate` will become 2020/12/24 23:00 with UTC tzinfo because I'm in UTC+1.

**Comment by aleksihakli** [comment]
@stefan-walluhn and @Mapiarz would you mind taking a look at #191 and see if it handles the timezones OK?

**Comment by bonokl** [comment]
I don't know if #191 solves the problem.

Imagine this:
server timezone is 'UTC', and user's timezone is 'Europe/Berlin' (+01:00 or +02:00 depending on the time of the year). 
Let's say user needs daily occurrences between 29.10. and 2.11. at 16:00h. 
User is creating a recurrence on 26.10. when his timezone is +02:00 compared to UTC. 
Current implementation will save dtstart as 14:00 UTC. And as result user would get next occurrences:
2022-10-29 14:00 UTC => 2022-10-17 16h Europe/Berlin (+02:00)
2022-10-30 14:00 UTC => 2022-10-17 16h Europe/Berlin (+02:00)
2022-11-01 14:00 UTC => 2022-10-17 15h Europe/Berlin (+01:00)
2022-11-02 14:00 UTC => 2022-10-17 15h Europe/Berlin (+01:00)

Because once the time is converted to UTC we don't know which time user wanted.

https://webis.helpshift.com/hc/en/3-pocket-informant/faq/177-recurring-events-and-daylight-saving-time-1634048685/

it should follow rule of the "creation" time zone, not server/UTC timezone,

**Comment by aleksihakli** [comment]
Good note @bonokl. Would you like to open a new issue for this, and possibly propose a fix in the form of a spec, or even better, a PR for the issue?
