### ISSUE TITLE
"Add Rule" "Add Date" buttons inoperative in Admin Inline.

### ISSUE THREAD

**Issue by TehCorwiz** [django-recurrence/django-recurrence#87]
django=1.9.12
django-recurrence=1.4.1

When using recurrence in django admin, if recurrence is a field on an inline model and an instance of the inline model is spawned using the "Add whatever" button then the "Add Rule" and "Add Date" buttons in recurrence do not function. The recurrence widget functions normally if the inline object is visible when loading the page.

**Comment by audiolion** [comment]
django==1.8.14
django-recurrence==1.4.1

Works for me:
https://imgur.com/a/QsGqd

**Comment by jpulec** [comment]
django==1.10.5
django-recurrence==1.4.1

This is also an issue for me. To be clear, yes, the buttons do appear when you click "Add MODEL_NAME" but upon clicking "Add Rule" and "Add Date", they do nothing. This only happens with recurrence fields add ed by the "Add MODEL_NAME" button. "Extra" inline recurrence fields seem to work just fine, if you specify an extra number on the ModelInline class.

**Comment by dominicrodger** [comment]
@jpulec/@TehCorwiz - do you have any idea why they don't work? Are there errors in your JS console or anything?

**Comment by jpulec** [comment]
It appears that it's related to how inlines are added. The django admin adds a new inline by cloning a sort of empty inline template. I believe that because it clones the empty templates this way, the click handlers that are setup in `recurrence.widget.Widget.init_dom()` and then in `recurrence.widget.AddButton.init_dom()` are not set up correctly. That's just a guess, but I think it's at least in the right direction.

There aren't any errors as a result of this. The click handlers just aren't fired at all when clicking the "Add Rule" or "Add Date" buttons.

**Comment by dominicrodger** [comment]
That makes sense to me. I'll take a look at this.

**Comment by zypro** [comment]
Having this issue with django 1.11.12 and django-recurrence 1.5.0.
It works only for the "extra" inlines. But by adding a new "lines" it doesn't work.

**Comment by pasevin** [comment]
looks like this is still an issue with inlines in django 2.1

**Comment by cwbutler** [comment]
I agree that this is still present 2 years later. Is there a work around? Besides not using it in inline forms?

**Comment by dominicrodger** [comment]
I've just pushed 1.9.0 to PyPI with this fix. Great work @pasevin! :champagne:
