### ISSUE TITLE
How Does this Library Handle dtstart?

### ISSUE THREAD

**Issue by jpulec** [django-recurrence/django-recurrence#90]
It isn't stated clearly in the docs anywhere, and it seems like there are conflicting opinions in both how this library handles dtstart. In the docstrings for `base.py` and `Recurrence` it does seem to indicate that `dtstart` is handled the according the RFC 2445, which uses it as both the starting point for recurrences and as the first recurrence returned.

This is in contrast to how `dateutil.rrule` handles it, which just uses `dtstart` as the starting point for recurrences and does not automatically add it as the first occurrence.

It looks like this can be a bit of a pain point for users. #50 #36 

Should this be better documented somewhere, to explicitly state that it doesn't follow the way `dateutil.rrule` handles `dtstart` and follows more closely to the spec. Or should changing the behavior be considered since it appears to cause issues? I recognize that this would be a big change.

**Comment by denisiko** [comment]
Didn't recognize that the inclusion of `dtstart` is indeed according to RFC 2445. Thanks @jpulec.

Then I would suggest to 1) [document it](https://django-recurrence.readthedocs.io/en/latest/usage/recurrence_field.html) and 2) maybe add an optional parameter `dtstart_include` to the between method that has `False` as default. This way it is clear how django-recurrence works for this case, it stays backwards compatible and users who are bothered by the default behavior can change it.

Any thoughts on that? If someone is interested I can make a pull request.

**Comment by jpulec** [comment]
@denisiko I'm biased, but I would really prefer a solution that supports some way following `dateutil.rrule` and not the spec, similar to what you described in 2).

Should this be something done as a `between()` parameter? Or does it make more sense to just add a setting for the entire library to support one behavior over the other? Or perhaps both?

**Comment by denisiko** [comment]
@jpulec I could think of a global settings constant in combination with a between param that overwrites the settings value if set. So it would be like:

1) dtstart is included if nothing is specified (according to spec)
2) dtstart inclusion is handled by user's global settings (if set properly)
3) dtstart is handled by optional between param if set explicitly

**Comment by jpulec** [comment]
@denisiko Is it just me, or would it seem to make more sense for the `between()` parameter to be the first place to check? That way a user could override it on a call by call basis. So we could do something like add a global setting called `RECURRENCE_DTSTART_INCLUDE` or whatever, and that value would default to `True`. Then the function signature for `between()` could specify `dtstart_include=settings.RECURRENCE_DTSTART_INCLUDE` as a default. That way you could override it easily on a call by call basis, or you could just flip the setting to have the default changed everywhere.

Does that make sense?

**Comment by denisiko** [comment]
@jpulec That's exactly what I meant :-) Think I wasn't clear on describing the order.

I already started working on this. I even named the global settings param exactly like you suggested :-) But after some thinking I came to the conclusion that it would be better to move my planned `between()` param `dtstart_inc` to the initialisation of the recurrence object and the definition of the recurrence field (like a `max_length` on a CharField). Then the global variable would be overwritten there.

I think it is easier this way because then you can e.g. define two different RecurrenceFields in a model where one includes `dtstart` and the other doesn't, without redefining `dtstart` for every single `between()`. Besides `dtstart` isn't only relevant for `between()`, but also for `after()` and some other functions as far as I can see from the code base.

Makes sense? I will have a PR ready by the end of the week.

**Comment by dominicrodger** [comment]
Thanks @jpulec and @denisiko for all your work here - sorry I'm a bit late to the party.

I'm open to being convinced otherwise, but I'm -1 on doing this with a setting - I think a parameter is much clearer. My concern with a setting is this: say you have two reusable apps installed which both depend on django-recurrence, and one wants the setting set, and one doesn't - how will that be resolved? If they both just use a parameter that works fine, but with a setting it's all or nothing for every consumer of ``settings.py``.

Thoughts?

**Comment by denisiko** [comment]
@dominicrodger I understand your concern. The way I would approach this is as following:

You have a variable in `base.py` which is reserved for the user's setting (for now I have placed it under the DAILY, WEEKLY etc. constants). It tries to get the user's `RECURRENCE_DTSTART_INCLUDE` setting and if it doesn't get a valid bool it defaults to `False`.

If another app wants a specific value for `RECURRENCE_DTSTART_INCLUDE` it just has to overwrite the variable in `base.py` (a setter function would make sense), so there's no need to access `django.conf.settings`. This should be made clear e.g. as a comment.

When I have the PR ready it's going to be clear I think.

**Comment by denisiko** [comment]
On the other hand it is not very elegant that you would have to explicitly overwrite the value on module level ever time you import the module and before you do anything with it. Maybe @dominicrodger is right and a parameter for the field and the object would be sufficient.

**Comment by douwevandermeij** [comment]
I still think the whole pull request #36 should be merged, maybe after some cleaning up. The current code is just wrong, my tests prove that. Also some weird tests with comments are resolved.
Maybe bump to a new major version without backwards compatibility, so people know their own code/fix to fix this is broken. In other words, people that had this problem and fixed it locally, know it's not ideal and can just drop the local fix.
Having a parameter to let people decide to fix this issue is not ideal, that's a fix for a fix. Please just fix the core.
Furthermore I found some more issues with weekly patterns and excluding dates, didn't fix that one yet.

**Comment by denisiko** [comment]
@douwevandermeij The code is not wrong or broken at this part, it follows a clear specification. Right at the beginning of the docs it says that Recurrence/Rule objects use a subset of RFC 2445. You can't just cherrypick from the spec because that would break consistency, so you also have to treat `dtstart` according to RFC 2445:
> The "DTSTART" property value, if specified, counts as the first occurrence.

Therefore your test function `test_occurrences_with_start_and_end_weekly_tuesdays()` doesn't prove anything in this direction and is wrong in the current state, because it is missing a crucial assertion.

I admit that the current `dtstart` practice might not be ideal (I was also in favor of merging your pull request because I didn't know the relevant part of the spec back then), but again I think it would be better to let the user decide if he wants to alter the default behavior. This would not be a fix for a fix, it would be the best compromise in my opinion.

Anyway: I created my own pull request #93 that enables the user to decide for himself how `dtstart` should be handled. Also tried to document it as clear as possible.

**Comment by douwevandermeij** [comment]
Ah, I didn't know that relevant spec either. Sounds like a weird spec, but it should be obeyed, fair enough. Your suggestion sounds plausible then; best of both worlds.

**Comment by denisiko** [comment]
Think so too, pretty weird idea. Just would be nice if this dtstart chapter closes.

**Comment by denisiko** [comment]
I think this issue can be closed now with #93.

**Comment by jpulec** [comment]
@denisiko I believe you're right. Glad to see this all get resolved. Great work and thanks!

**Comment by denisiko** [comment]
No problem and thanks!
